### ISSUE TITLE
copy to clipboard convenience button

### ISSUE THREAD

**Issue by aaronmyatt** [devsdeck/devsdeck#53]
All code block/lines should be conveniently copy-able to the clipboard!!!!!!

**Comment by luizpicolo** [comment]
I will do that now [#53](https://github.com/luizpicolo/devsdeck/tree/issue%2353)

**Comment by hosseintoussi** [comment]
awesome @luizpicolo thanks a lot.

**Comment by aaronmyatt** [comment]
seems I just duplicated this issue - smart.

**Comment by hosseintoussi** [comment]
done
